client_id: '6204eb0c574646308d321d764685ff74'
client_secret: '9094bd9a28a44881a40680b5845c3c84'
access_token_url: 'https://accounts.spotify.com/api/token'
auth_url: 'http://accounts.spotify.com/authorize'
api_version: 'v1'
api_url: 'https://api.spotify.com'
auth_method: 'AUTHORIZATION_CODE'